language: python
python:
  - "3.5"
before_install:
  - mv travis_secrets.yaml secrets.yaml
install:
  - pip3 install homeassistant
script:
  - sudo mkdir /ssl/
  - sudo touch /ssl/cert.pem
  - sudo touch /ssl/key.pem
  - hass -c . --script check_config