#- id: '001'
#  alias: Night Mode
#  trigger:
#  - at: '23:00'
#    platform: time
#  condition:
#  - condition: state
#    entity_id: group.people
#    state: home
#  action:
#  - service: script.turn_on
#    entity_id: script.arlo_control
#    data_template:
#      entity_id: script.arlo_control
#      variables:
#        arloentity: internal
#        arlomode: armed
- id: '002'
  alias: Away Mode
  trigger:
  - entity_id: group.people
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - service: script.turn_on
    entity_id: script.arlo_control
    data_template:
      entity_id: script.arlo_control
      variables:
        arloentity: internal
        arlomode: armed
  - service: script.turn_on
    entity_id: script.arlo_control
    data_template:
      entity_id: script.arlo_control
      variables:
        arloentity: external
        arlomode: armed
  - service: light.turn_off
    entity_id: all
  - service: script.turn_on
    entity_id: script.dyson_control_away
- id: '003'
  alias: Home Mode (day)
  trigger:
  - entity_id: group.people
    from: not_home
    platform: state
    to: home
  condition:
  - condition: time
    after: 06:00
    before: '23:00'
  action:
  - service: script.turn_on
    entity_id: script.arlo_control
    data_template:
      entity_id: script.arlo_control
      variables:
        arloentity: internal
        arlomode: disarmed
- id: '003'
  alias: Home Mode (evening)
  trigger:
  - entity_id: group.people
    from: not_home
    platform: state
    to: home
  condition:
  - before: '23:00'
    condition: time
  - after: sunset
    after_offset: -00:30
    condition: sun
  action:
  - service: script.turn_on
    entity_id: script.arlo_control
    data_template:
      entity_id: script.arlo_control
      variables:
        arloentity: internal
        arlomode: disarmed
  - service: light.turn_on
    entity_id: light.hallway_2
- id: '004'
  alias: Home Mode (night)
  trigger:
  - entity_id: group.people
    from: not_home
    platform: state
    to: home
  condition:
  - after: '23:00'
    condition: time
  action:
  - service: script.turn_on
    entity_id: script.home_mode_night
    data_template:
      entity_id: script.home_mode_night
      variables:
        arloentity: internal
- id: '005'
  alias: Backup
  trigger:
  - at: '02:00'
    platform: time
  condition: []
  action:
  - service: script.turn_on
    entity_id: script.snapshot_and_cloud_backup
#- id: '006'
#  alias: Reboot HA
#  trigger:
#  - at: '04:00'
#    platform: time
#  condition: []
#  action:
#  - service: homeassistant.restart

- id: '100'
  alias: Activate Night Mode
  trigger: 
    platform: state
    entity_id: input_boolean.nightmode
    to: 'on'
  action:
  - service: script.turn_on
    entity_id: script.arlo_control
    data_template:
      entity_id: script.arlo_control
      variables:
        arloentity: internal
        arlomode: armed
  - service: light.turn_off
    entity_id: light.hallway
  - service: light.turn_off
    entity_id: light.living_room
  - service: light.turn_off
    entity_id: light.spare_bedroom
  - service: light.turn_off
    entity_id: light.bedroom
  - service: hue.hue_activate_scene
    data:
      group_name: "Craig's Bedside Light"  
      scene_name: "Bedtime"

- id: '101'
  alias: Deactivate Night Mode
  trigger: 
    platform: state
    entity_id: input_boolean.nightmode
    to: 'off'
  action:
  - service: script.turn_on
    entity_id: script.arlo_control
    data_template:
      entity_id: script.arlo_control
      variables:
        arloentity: internal
        arlomode: disarmed
  - service: hue.hue_activate_scene
    data:
      group_name: "Bedroom"  
      scene_name: "Crabbey"

