#Arlo login
aarlo:
 username: !secret arlo_user
 password: !secret arlo_pass

# Cameras
camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

# Alarm Control Panels
alarm_control_panel:
  - platform: aarlo
    home_mode_name: disarmed
    away_mode_name: armed
    #trigger_time: 30
    #alarm_volume: 8

# Arlo Sensors
binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    - ding

sensor:
  - platform: aarlo
    monitored_conditions:
    - last_capture
    - total_cameras
    - battery_level
    - captured_today
    - signal_strength

script:
  arlo_control:
    sequence:
      - service: alarm_control_panel.aarlo_set_mode
        data_template:
          entity_id: "alarm_control_panel.aarlo_{{ arloentity }}"
          mode: "{{ arlomode }}"

  arlo_control_temporarydisable:
    sequence:
      - service: alarm_control_panel.aarlo_set_mode
        data_template:
          entity_id: "alarm_control_panel.aarlo_{{ arloentity }}"
          mode: "disarmed"
      - delay: '01:00'
      - service: alarm_control_panel.aarlo_set_mode
        data_template:
          entity_id: "alarm_control_panel.aarlo_{{ arloentity }}"
          mode: "armed"

  arlo_control_disarm_internal:
    alias: Disarm Internal Arlo
    sequence:
      - service: alarm_control_panel.aarlo_set_mode
        data_template:
          entity_id: "alarm_control_panel.aarlo_internal"
          mode: "disarmed"

  arlo_control_arm_internal:
    alias: Arm Internal Arlo
    sequence:
      - service: alarm_control_panel.aarlo_set_mode
        data_template:
          entity_id: "alarm_control_panel.aarlo_internal"
          mode: "armed"

  arlo_control_disarm_external:
    alias: Disarm External Arlo
    sequence:
      - service: alarm_control_panel.aarlo_set_mode
        data_template:
          entity_id: "alarm_control_panel.aarlo_external"
          mode: "disarmed"

  arlo_control_arm_external:
    alias: Arm External Arlo
    sequence:
      - service: alarm_control_panel.aarlo_set_mode
        data_template:
          entity_id: "alarm_control_panel.aarlo_external"
          mode: "armed"
          
          
influxdb:
  tags:
    instance: prod
    source: hass
    sourcetype: arlo
    sensor: battery
  include:
    entities:
       - sensor.aarlo_battery_level_front_door
       - sensor.aarlo_battery_level_driveway
       - sensor.aarlo_battery_level_garden_gate
       - sensor.aarlo_battery_level_garden_rear
       - sensor.aarlo_battery_level_hallway
       - sensor.aarlo_battery_level_kitchen
       - sensor.aarlo_battery_level_landing
       - sensor.aarlo_battery_level_living_room


