group:
###############################################################################
# Groups  
############################################################################### 


  darksky:
    name: Darksky Weather
    view: no
    entities:
      - sensor.dark_sky_summary
      - sensor.dark_sky_icon
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_temperature
      - sensor.dark_sky_temperature_high
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_cloud_cover
      - sensor.dark_sky_humidity

sensor:
  - platform: darksky
    api_key: !secret darksky
    monitored_conditions:
      - summary
      - icon
      - precip_probability
      - temperature
      - wind_speed
      - apparent_temperature
      - cloud_cover
      - humidity
      - hourly_summary
      - temperature_high
