group:

  darksky:
    name: Darksky Weather
    view: no
    entities:
      - sensor.dark_sky_summary
      - sensor.dark_sky_icon
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_temperature
      - sensor.dark_sky_temperature_high
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_humidity

sensor:
  - platform: darksky
    api_key: !secret darksky
    forecast:
      - 0
      - 1
      - 2

    hourly_forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7


    monitored_conditions:
      - summary
      - icon
      - precip_type
      - precip_probability
      - precip_intensity
      - temperature
      - temperature_high
      - wind_speed
      - apparent_temperature
      - apparent_temperature_high
      - cloud_cover
      - humidity
      - hourly_summary
      - uv_index

